### PR TITLE
Fix indexing for chains in different threads

### LINKED ISSUE #153: `BoundsError` when sampling with `MCMCThreads`
### Minimal working example

```julia
using Turing

function sample_chains(chain_count)
    try
        ### The example from https://turinglang.org/docs/tutorials/docs-12-using-turing-guide/#multithreaded-sampling
        @model function gdemo(x)
            s² ~ InverseGamma(2, 3)
            m ~ Normal(0, sqrt(s²))
        
            for i in eachindex(x)
                x[i] ~ Normal(m, sqrt(s²))
            end
        end
        
        model = gdemo([1.5, 2.0])
        
        # Sample four chains using multiple threads, each with 1000 samples.
        return sample(model, NUTS(), MCMCThreads(), 1000, chain_count)
    
    catch BoundsError
        return nothing
    end
end

samples = [sample_chains(chain_count) for chain_count in 1:30]

println("Thread count: $(Threads.nthreads())")
for i in eachindex(samples)
    isnothing(samples[i]) && println("BoundsError with $i chains")
end
```

### Description

When I try to sample multiple chains in parallel using `Turing.sample` with `MCMCThreads()`, I get `BoundsError` with _some_ values of the `nchains` parameter.

It only occurs to me with values, where `nchains > Threads.nthreads()`. I am not sure if this is relevant as the errors do not occur for all such values though.

I get the following output by running the provided MWE:
```julia-repl
...

Thread count: 6
BoundsError with 7 chains
BoundsError with 8 chains
BoundsError with 9 chains
BoundsError with 13 chains
BoundsError with 14 chains
BoundsError with 19 chains

julia> 
```

### Julia version info

<details><summary>versioninfo()</summary>

```julia-repl
julia> versioninfo()
Julia Version 1.11.2
Commit 5e9a32e7af2 (2024-12-01 20:02 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 12 × Apple M3 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m2)
Threads: 6 default, 0 interactive, 3 GC (on 6 virtual cores)
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_EDITOR = code
  DYLD_FALLBACK_LIBRARY_PATH = /Users/soldasim/.julia/artifacts/9f138443d219d493bff0e1dbe24fcb76a8bd3fe6/lib:/Users/soldasim/.julia/artifacts/06b4eca2da96ea8e2e910741b815dd66bbee8baa/lib:/Users/soldasim/.julia/artifacts/5b90ad21b4b1af3a9446241fb5afe3e3b3eda941/lib:/Users/soldasim/.julia/juliaup/julia-1.11.2+0.aarch64.apple.darwin14/lib/julia:/Users/soldasim/.julia/artifacts/d3baa6c3df75e116ea8238482f865f35ff156810/lib:/Users/soldasim/.julia/artifacts/9410bad2635eda2239b4a72ba4316c4aa8f5b76e/lib:/Users/soldasim/.julia/artifacts/3b568c51fbf75bfe59ac69d26b176034fdd63ebb/lib:/Users/soldasim/.julia/artifacts/21209a2ac399ce693d73daf1aa8d670fbc84d70f/lib:/Users/soldasim/.julia/artifacts/07e6bd5ae846b525d0c43be96788967cfccb923b/lib:/Users/soldasim/.julia/artifacts/de2b167794a02c351290cd50eb02bef6dada8faf/lib:/Users/soldasim/.julia/artifacts/a0dcd10a8f34e5421da9b9a3266c0bf534ee03e9/lib:/Users/soldasim/.julia/artifacts/becfd6f89f1a272ace2375b067f1153515ca70b3/lib:/Users/soldasim/.julia/artifacts/1ed65d60dbf4c95b71bed5c28505e017ea1de760/lib:/Users/soldasim/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib:/Users/soldasim/.julia/artifacts/1994697285dfe8747ff7ec6927666edc88750202/lib:/Users/soldasim/.julia/artifacts/c5d5b7c7e77b04af2eabde40ebbf379932d8bfd7/lib:/Users/soldasim/.julia/artifacts/81e1d2f3a1459f121eaae539b9549e9e740a6c62/lib:/Users/soldasim/.julia/artifacts/a3e73ecf5d803bb3792a23f0382a2b5573383647/lib:/Users/soldasim/.julia/artifacts/67723a86975c82b43f01cda306999b382d3435f0/lib:/Users/soldasim/.julia/artifacts/115f3a18328d7b88e31c9e3f095aeb12eb381710/lib:/Users/soldasim/.julia/artifacts/ca2831bf6edc5088aec5b329ea98364951d6cad0/lib:/Users/soldasim/.julia/artifacts/477447566a69a531a7a3f8e0130cbfe460b37eec/lib:/Users/soldasim/.julia/artifacts/b58891667c46c467bd51be0e963c1ef1f0314934/lib:/Users/soldasim/.julia/artifacts/0db9c3f6cf936a0da49e2ba954ba3e10bed6ad72/lib:/Users/soldasim/.julia/artifacts/1a7e22e66b523d9cb884cf85c3ec065b5fb3e5c3/lib:/Users/soldasim/.julia/artifacts/e33c9389fd079973c7a7520d36779612df7ec447/lib:/Users/soldasim/.julia/artifacts/83ff444c229f9dd64a13999123a4eb14e632d67a/lib:/Users/soldasim/.julia/artifacts/6095fcd268ea712c0f786f5ff1a45bf0eb7b005e/lib:/Users/soldasim/.julia/artifacts/7ead0a440ba045155db235bff6602a984f08a651/lib:/Users/soldasim/.julia/artifacts/9d8a957aa3387b17b8639251016c87710db1a175/lib:/Users/soldasim/.julia/artifacts/63d48e4aab8721470f588bdeb1e2b462ee3b6a68/lib:/Users/soldasim/.julia/artifacts/b1d1f92386064b705995c9fb864a4a1021883132/lib:/Users/soldasim/.julia/artifacts/7fab57b870c361fd74fc9164e66e4d1f82f24640/lib:/Users/soldasim/.julia/artifacts/932f282690a789f3744abcd83fb9f68ba7ed4c19/lib:/Users/soldasim/.julia/artifacts/4b3b2d79556cc3aef6e3d8a234649cc85b91bb87/lib:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtConcurrent.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtCore.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtDBus.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtGui.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtNetwork.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtOpenGL.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtPrintSupport.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtSql.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtTest.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtWidgets.framework/Versions/A:/Users/soldasim/.julia/artifacts/7f2122f84c49e5b75c5b4cbf46bbdeb3b0ffc5da/lib/QtXml.framework/Versions/A:/Users/soldasim/.julia/artifacts/89e9e24387fcba2a6828b09d4c2d32eadc60e937/lib:/Users/soldasim/.julia/juliaup/julia-1.11.2+0.aarch64.apple.darwin14/bin/../lib/julia:/Users/soldasim/.julia/juliaup/julia-1.11.2+0.aarch64.apple.darwin14/bin/../lib:

julia> 
```
</details>

### Manifest

<details><summary>]st --manifest</summary>

```julia-repl
(examples) pkg> st --manifest
Status `~/Documents/julia-pkg/BOSS.jl/examples/Manifest.toml`
  [47edcb42] ADTypes v1.11.0
  [621f4979] AbstractFFTs v1.5.0
  [99985d1d] AbstractGPs v0.5.21
  [80f14c24] AbstractMCMC v5.6.0
⌅ [7a57a42e] AbstractPPL v0.9.0
  [1520ce14] AbstractTrees v0.4.5
  [7d9f7c33] Accessors v0.1.39
  [79e6a3ab] Adapt v4.1.1
  [0bf59076] AdvancedHMC v0.6.4
  [5b7e9947] AdvancedMH v0.8.5
  [576499cb] AdvancedPS v0.6.0
⌅ [b5ca4192] AdvancedVI v0.2.11
  [66dad0bd] AliasTables v1.1.3
  [dce04be8] ArgCheck v2.4.0
  [4fba245c] ArrayInterface v7.18.0
  [a9b6321e] Atomix v1.0.1
  [13072b0f] AxisAlgorithms v1.1.0
  [39de3d68] AxisArrays v0.4.7
  [15052f3f] BOSS v0.3.2 `..`
  [198e06fe] BangBang v0.4.3
  [9718e550] Baselet v0.1.1
  [76274a88] Bijectors v0.15.2
  [d1d4a3ce] BitFlags v0.1.9
  [082447d4] ChainRules v1.72.2
  [d360d2e6] ChainRulesCore v1.25.1
  [9e997f8a] ChangesOfVariables v0.1.9
  [944b1d66] CodecZlib v0.7.6
  [35d6a980] ColorSchemes v3.27.1
  [3da002f7] ColorTypes v0.12.0
  [c3611d14] ColorVectorSpace v0.11.0
  [5ae59095] Colors v0.13.0
  [861a8166] Combinatorics v1.0.2
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.1
  [34da2185] Compat v4.16.0
  [a33af91c] CompositionsBase v0.1.2
  [f0e56b4a] ConcurrentUtilities v2.4.3
  [88cd18e8] ConsoleProgressMonitor v0.1.2
  [187b0558] ConstructionBase v1.5.8
  [d38c429a] Contour v0.6.3
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.18.20
  [e2d170a0] DataValueInterfaces v1.0.0
  [244e2a9f] DefineSingletons v0.1.2
  [8bb1440f] DelimitedFiles v1.9.1
  [b429d917] DensityInterface v0.4.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.6.28
  [b4f34e82] Distances v0.10.12
  [31c24e10] Distributions v0.25.116
  [ced4e74d] DistributionsAD v0.6.57
  [ffbed154] DocStringExtensions v0.9.3
  [366bfd00] DynamicPPL v0.32.2
  [cad2338a] EllipticalSliceSampling v2.0.0
  [4e289a0a] EnumX v1.0.4
  [460bff9d] ExceptionUnwrapping v0.1.11
  [e2ba6199] ExprTools v0.1.10
⌅ [6b7a57c9] Expronicon v0.8.5
  [c87230d0] FFMPEG v0.4.2
  [7a1cc6ca] FFTW v1.8.0
  [9aa1b823] FastClosures v0.3.2
  [1a297f60] FillArrays v1.13.0
  [6a86dc24] FiniteDiff v2.26.2
  [53c48c17] FixedPointNumbers v0.8.5
  [1fa38f19] Format v1.3.7
  [f6369f11] ForwardDiff v0.10.38
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
⌅ [d9f16b24] Functors v0.4.12
  [46192b85] GPUArraysCore v0.2.0
  [28b8d3ca] GR v0.73.10
  [42e2da0e] Grisu v1.0.2
  [cd3eb016] HTTP v1.10.15
  [34004b35] HypergeometricFunctions v0.3.25
  [22cec73e] InitialValues v0.3.1
  [505f98c9] InplaceOps v0.3.0
  [a98d9a8b] Interpolations v0.15.1
  [8197267c] IntervalSets v0.7.10
  [3587e190] InverseFunctions v0.1.17
  [41ab1584] InvertedIndices v1.3.1
  [92d709cd] IrrationalConstants v0.2.2
  [c8e1da08] IterTools v1.10.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [1019f520] JLFzf v0.1.9
  [692b3bcd] JLLWrappers v1.7.0
  [682c06a0] JSON v0.21.4
  [63c18a36] KernelAbstractions v0.9.31
  [5ab0869b] KernelDensity v0.6.9
  [ec8451be] KernelFunctions v0.10.64
  [5be7bae1] LBFGSB v0.4.1
  [8ac3fa9e] LRUCache v1.6.1
  [b964fa9f] LaTeXStrings v1.4.0
  [23fbe1c1] Latexify v0.16.5
  [a5e1c1ea] LatinHypercubeSampling v1.9.0
  [1d6d02ad] LeftChildRightSiblingTrees v0.2.0
  [6f1fad26] Libtask v0.8.8
  [d3d80556] LineSearches v7.3.0
  [6fdf6af0] LogDensityProblems v2.1.2
  [996a588d] LogDensityProblemsAD v1.13.0
  [2ab3a3ac] LogExpFunctions v0.3.29
  [e6f89c97] LoggingExtras v1.1.0
  [c7f686f2] MCMCChains v6.0.7
  [be115224] MCMCDiagnosticTools v0.3.14
  [e80e1ace] MLJModelInterface v1.11.0
  [d8e11817] MLStyle v0.4.17
  [1914dd2f] MacroTools v0.5.15
  [dbb5928d] MappedArrays v0.4.2
  [739be429] MbedTLS v1.1.9
  [442fdcdd] Measures v0.3.2
  [128add7d] MicroCollections v0.2.0
  [e1d29d7a] Missings v1.2.0
  [d41bc354] NLSolversBase v7.8.3
  [872c559c] NNlib v0.9.26
  [77ba4419] NaNMath v1.0.2
  [86f7a689] NamedArrays v0.10.3
  [c020b1a1] NaturalSort v1.0.0
  [6fe1bfb0] OffsetArrays v1.15.0
  [4d8831e6] OpenSSL v1.4.3
  [429524aa] Optim v1.10.0
  [3bd65402] Optimisers v0.4.4
  [7f7a1694] Optimization v4.0.5
  [bca83a33] OptimizationBase v2.4.0
  [36348300] OptimizationOptimJL v0.4.1
  [72f8369c] OptimizationPRIMA v0.3.0
  [bac558e1] OrderedCollections v1.7.0
  [90014a1f] PDMats v0.11.31
  [0a7d04aa] PRIMA v0.2.2
  [d96e819e] Parameters v0.12.3
  [69de0a69] Parsers v2.8.1
  [b98c9c47] Pipe v1.3.0
  [ccf2f8ad] PlotThemes v3.3.0
  [995b91a9] PlotUtils v1.4.3
  [91a5bcdd] Plots v1.40.9
  [85a6dd25] PositiveFactorizations v0.2.4
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [08abe8d2] PrettyTables v2.4.0
  [33c8b6b6] ProgressLogging v0.1.4
  [92933f4c] ProgressMeter v1.10.2
  [43287f4e] PtrArrays v1.2.1
  [1fd47b50] QuadGK v2.11.1
  [74087812] Random123 v1.7.0
  [e6cf234a] RandomNumbers v1.6.0
  [b3c3ace0] RangeArrays v0.3.2
  [c84ed2f1] Ratios v0.4.5
  [c1ae055f] RealDot v0.1.0
  [3cdcf5f2] RecipesBase v1.3.4
  [01d81517] RecipesPipeline v0.6.12
  [731186ca] RecursiveArrayTools v3.27.4
  [189a3867] Reexport v1.2.2
  [05181044] RelocatableFolders v1.0.1
  [ae029012] Requires v1.3.0
  [79098fc4] Rmath v0.8.0
  [f2b01f46] Roots v2.2.3
  [7e49a35a] RuntimeGeneratedFunctions v0.5.13
⌅ [26aad666] SSMProblems v0.1.1
  [0bca4576] SciMLBase v2.70.0
  [c0aeaf25] SciMLOperators v0.3.12
  [53ae85a6] SciMLStructures v1.6.1
  [30f210dd] ScientificTypesBase v3.0.0
  [6c6a2e73] Scratch v1.2.1
  [efcf1570] Setfield v1.1.1
  [992d4aef] Showoff v1.0.3
  [777ac1f9] SimpleBufferStream v1.2.0
  [ce78b400] SimpleUnPack v1.1.0
  [a2af1166] SortingAlgorithms v1.2.1
  [9f842d2f] SparseConnectivityTracer v0.6.9
  [dc90abb0] SparseInverseSubset v0.1.2
  [0a514795] SparseMatrixColorings v0.4.10
  [276daf66] SpecialFunctions v2.5.0
  [171d559e] SplittablesBase v0.1.15
  [860ef19b] StableRNGs v1.0.2
  [90137ffa] StaticArrays v1.9.10
  [1e83bf80] StaticArraysCore v1.4.3
  [64bff920] StatisticalTraits v3.4.0
  [10745b16] Statistics v1.11.1
  [82ae8749] StatsAPI v1.7.0
  [2913bbd2] StatsBase v0.34.4
  [4c63d2b9] StatsFuns v1.3.2
  [892a3eda] StringManipulation v0.4.0
⌃ [09ab397b] StructArrays v0.6.21
  [2efcf032] SymbolicIndexingInterface v0.3.37
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.0
  [62fd8b95] TensorCore v0.1.1
  [5d786b92] TerminalLoggers v0.1.7
  [9f7883ad] Tracker v0.2.37
  [3bb67fe8] TranscodingStreams v0.11.3
  [28d57a85] Transducers v0.4.84
  [fce5fe82] Turing v0.35.5
  [c3b1956e] TypeUtils v1.4.0
  [5c2747f8] URIs v1.5.1
  [3a884ed6] UnPack v1.0.2
  [1cfade01] UnicodeFun v0.4.1
  [1986cc42] Unitful v1.22.0
  [45397f5d] UnitfulLatexify v1.6.4
  [013be700] UnsafeAtomics v0.3.0
  [41fe7b60] Unzip v0.2.0
  [efce3f68] WoodburyMatrices v1.0.0
  [700de1a5] ZygoteRules v0.2.5
  [6e34b625] Bzip2_jll v1.0.8+4
  [83423d85] Cairo_jll v1.18.2+1
  [ee1fde0b] Dbus_jll v1.14.10+0
  [2702e6a9] EpollShim_jll v0.0.20230411+1
  [2e619515] Expat_jll v2.6.4+3
⌅ [b22a6f82] FFMPEG_jll v4.4.4+1
  [f5851436] FFTW_jll v3.3.10+3
  [a3f928ae] Fontconfig_jll v2.15.0+0
  [d7e528f0] FreeType2_jll v2.13.3+1
  [559328eb] FriBidi_jll v1.0.16+0
  [0656b61e] GLFW_jll v3.4.0+2
  [d2c73de3] GR_jll v0.73.10+0
  [78b55507] Gettext_jll v0.21.0+0
  [7746bdde] Glib_jll v2.82.4+0
  [3b182d85] Graphite2_jll v1.3.14+1
  [2e76f6c2] HarfBuzz_jll v8.5.0+0
  [1d5cc7b8] IntelOpenMP_jll v2024.2.1+0
  [aacddb02] JpegTurbo_jll v3.1.1+0
  [c1c5ebd0] LAME_jll v3.100.2+0
  [88015f11] LERC_jll v4.0.1+0
  [1d63c593] LLVMOpenMP_jll v18.1.7+0
  [dd4b983a] LZO_jll v2.10.2+3
  [81d17ec3] L_BFGS_B_jll v3.0.1+0
⌅ [e9f186c6] Libffi_jll v3.2.2+2
  [d4300ac3] Libgcrypt_jll v1.11.0+0
  [7e76a0d4] Libglvnd_jll v1.7.0+0
  [7add5ba3] Libgpg_error_jll v1.51.1+0
  [94ce4f54] Libiconv_jll v1.17.0+1
  [4b2f31a3] Libmount_jll v2.40.2+2
  [89763e89] Libtiff_jll v4.7.1+0
  [38a345b3] Libuuid_jll v2.40.2+2
  [856f044c] MKL_jll v2024.2.0+0
  [e7412a2a] Ogg_jll v1.3.5+1
  [458c3c95] OpenSSL_jll v3.0.15+3
  [efe28fd5] OpenSpecFun_jll v0.5.6+0
  [91d4177d] Opus_jll v1.3.3+0
  [eead6e0c] PRIMA_jll v0.7.1+0
  [36c8627f] Pango_jll v1.55.5+0
⌅ [30392449] Pixman_jll v0.43.4+0
⌅ [c0090381] Qt6Base_jll v6.7.1+1
  [629bc702] Qt6Declarative_jll v6.7.1+2
  [ce943373] Qt6ShaderTools_jll v6.7.1+1
  [e99dba38] Qt6Wayland_jll v6.7.1+1
  [f50d1b31] Rmath_jll v0.5.1+0
  [a44049a8] Vulkan_Loader_jll v1.3.243+0
  [a2964d1f] Wayland_jll v1.21.0+2
  [2381bf8a] Wayland_protocols_jll v1.36.0+0
  [02c8fc9c] XML2_jll v2.13.5+0
  [aed1982a] XSLT_jll v1.1.42+0
  [ffd25f8a] XZ_jll v5.6.4+0
  [f67eecfb] Xorg_libICE_jll v1.1.1+0
  [c834827a] Xorg_libSM_jll v1.2.4+0
  [4f6342f7] Xorg_libX11_jll v1.8.6+3
  [0c0b7dd1] Xorg_libXau_jll v1.0.11+3
  [935fb764] Xorg_libXcursor_jll v1.2.3+0
  [a3789734] Xorg_libXdmcp_jll v1.1.4+3
  [1082639a] Xorg_libXext_jll v1.3.6+3
  [d091e8ba] Xorg_libXfixes_jll v6.0.0+0
  [a51aa0fd] Xorg_libXi_jll v1.8.2+0
  [d1454406] Xorg_libXinerama_jll v1.1.5+0
  [ec84b674] Xorg_libXrandr_jll v1.5.4+0
  [ea2f1a96] Xorg_libXrender_jll v0.9.11+1
  [14d82f49] Xorg_libpthread_stubs_jll v0.1.1+3
  [c7cfdc94] Xorg_libxcb_jll v1.17.0+3
  [cc61e674] Xorg_libxkbfile_jll v1.1.2+1
  [e920d4aa] Xorg_xcb_util_cursor_jll v0.1.4+0
  [12413925] Xorg_xcb_util_image_jll v0.4.0+1
  [2def613f] Xorg_xcb_util_jll v0.4.0+1
  [975044d2] Xorg_xcb_util_keysyms_jll v0.4.0+1
  [0d47668e] Xorg_xcb_util_renderutil_jll v0.3.9+1
  [c22f9ab0] Xorg_xcb_util_wm_jll v0.4.1+1
  [35661453] Xorg_xkbcomp_jll v1.4.6+1
  [33bec58e] Xorg_xkeyboard_config_jll v2.39.0+0
  [c5fb5394] Xorg_xtrans_jll v1.5.0+3
  [3161d3a3] Zstd_jll v1.5.7+0
  [35ca27e7] eudev_jll v3.2.9+0
  [214eeab7] fzf_jll v0.56.3+0
  [1a1c6b14] gperf_jll v3.1.1+1
  [a4ae2306] libaom_jll v3.11.0+0
  [0ac62f75] libass_jll v0.15.2+0
  [1183f4f0] libdecor_jll v0.2.2+0
  [2db6ffa8] libevdev_jll v1.11.0+0
  [f638f0a6] libfdk_aac_jll v2.0.3+0
  [36db933b] libinput_jll v1.18.0+0
  [b53b4c65] libpng_jll v1.6.45+0
  [f27f6e37] libvorbis_jll v1.3.7+2
  [009596ad] mtdev_jll v1.1.6+0
  [1317d2d5] oneTBB_jll v2021.12.0+0
⌅ [1270edf5] x264_jll v2021.5.5+0
⌅ [dfaa095f] x265_jll v3.5.0+0
  [d8fb68d0] xkbcommon_jll v1.4.1+2
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [a63ad114] Mmap v1.11.0
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.11.0
  [de0858da] Printf v1.11.0
  [3fa0cd96] REPL v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [1a1011a3] SharedArrays v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.11.0
  [f489334b] StyledStrings v1.11.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] LibCURL_jll v8.6.0+0
  [e37daf67] LibGit2_jll v1.7.2+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.6+0
  [14a3606d] MozillaCACerts_jll v2023.12.12
  [4536629a] OpenBLAS_jll v0.3.27+1
  [05823500] OpenLibm_jll v0.8.1+2
  [efcefdf7] PCRE2_jll v10.42.0+1
  [bea87d4a] SuiteSparse_jll v7.7.0+0
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
  [8e850ede] nghttp2_jll v1.59.0+0
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`

(examples) pkg> 
```
</details>

### PR DESCRIPTION
**Pull request by penelopeysm**
Closes #153 

If there were 6 threads and 9 chains, the previous code (https://github.com/TuringLang/AbstractMCMC.jl/blob/5a3b155ed0b8b7e97810005a22e013b8b4da2bb2/src/sample.jl#L441-L445) would generate the following `chainidxs` for each thread

```
1:2
3:4
5:6
7:8
9:10
11:10
```

Somewhere later on (probably in the fifth thread with `chainidxs = 9:10`) this causes indexing errors as we only have a vector of size 9.

This PR changes it such that for the same inputs (6 threads and 9 chains) it generates the following `chainidxs`

```
1:2
3:4
5:6
7:7
8:8
9:9
```

The error in #153 is fixed

```julia
julia> samples = [sample_chains(chain_count) for chain_count in 1:30]
30-element Vector{Chains{Float64, AxisArrays.AxisArray{Float64, 3, Array{Float64, 3}, Tuple{AxisArrays.Axis{:iter, StepRange{Int64, Int64}}, AxisArrays.Axis{:var, Vector{Symbol}}, AxisArrays.Axis{:chain, UnitRange{Int64}}}}, Missing, @NamedTuple{parameters::Vector{Symbol}, internals::Vector{Symbol}}}}:
 MCMC chain (1000×14×1 Array{Float64, 3})
 MCMC chain (1000×14×2 Array{Float64, 3})
 MCMC chain (1000×14×3 Array{Float64, 3})
 MCMC chain (1000×14×4 Array{Float64, 3})
 MCMC chain (1000×14×5 Array{Float64, 3})
 MCMC chain (1000×14×6 Array{Float64, 3})
 MCMC chain (1000×14×7 Array{Float64, 3})
 MCMC chain (1000×14×8 Array{Float64, 3})
 MCMC chain (1000×14×9 Array{Float64, 3})
 MCMC chain (1000×14×10 Array{Float64, 3})
 MCMC chain (1000×14×11 Array{Float64, 3})
 MCMC chain (1000×14×12 Array{Float64, 3})
 MCMC chain (1000×14×13 Array{Float64, 3})
 MCMC chain (1000×14×14 Array{Float64, 3})
 MCMC chain (1000×14×15 Array{Float64, 3})
 MCMC chain (1000×14×16 Array{Float64, 3})
 MCMC chain (1000×14×17 Array{Float64, 3})
 MCMC chain (1000×14×18 Array{Float64, 3})
 MCMC chain (1000×14×19 Array{Float64, 3})
 MCMC chain (1000×14×20 Array{Float64, 3})
 MCMC chain (1000×14×21 Array{Float64, 3})
 MCMC chain (1000×14×22 Array{Float64, 3})
 MCMC chain (1000×14×23 Array{Float64, 3})
 MCMC chain (1000×14×24 Array{Float64, 3})
 MCMC chain (1000×14×25 Array{Float64, 3})
 MCMC chain (1000×14×26 Array{Float64, 3})
 MCMC chain (1000×14×27 Array{Float64, 3})
 MCMC chain (1000×14×28 Array{Float64, 3})
 MCMC chain (1000×14×29 Array{Float64, 3})
 MCMC chain (1000×14×30 Array{Float64, 3})

julia> println("Thread count: $(Threads.nthreads())")
Thread count: 6

julia> for i in eachindex(samples)
           isnothing(samples[i]) && println("BoundsError with $i chains")
       end
```

### CODE REVIEW

File: src/sample.jl [hunk 1]
```diff
@@ -436,13 +447,8 @@ function mcmcsample(
...
                 try
-                    Distributed.@sync for (i, _rng, _model, _sampler) in
-                                          zip(1:nchunks, rngs, models, samplers)
-                        chainidxs = if i == nchunks
-                            ((i - 1) * chunksize + 1):nchains
-                        else
-                            ((i - 1) * chunksize + 1):(i * chunksize)
-                        end
+                    Distributed.@sync for (chainidxs, _rng, _model, _sampler) in
+                                          zip(chain_index_groups, rngs, models, samplers)
```
Comment (devmotion) [inline src/sample.jl:451]: AFAICT you could compute the chunks on the fly:
```suggestion
                    Distributed.@sync for (i, _rng, _model, _sampler) in
                                          zip(interval, rngs, models, samplers)
                        chainidx_lo = (i - 1) * m + min(n, i - 1) + 1
                        chainidx_hi = chainidx_lo + m - (i > n)
                        chainidxs = chainidx_lo:chainidx_hi
```

Comment (penelopeysm) [reply src/sample.jl:451]: Hmm, yes, we could. I think subtracting i > n is a bit too smart for me, though. Let me write up something similar...

Comment (penelopeysm) [reply src/sample.jl]: Ok, let me know what you think 🙂

**Comment by penelopeysm** [comment]
@mhauru the logic itself feels too basic to be worth testing to me 😅. I checked again locally with the most recent commit and it still behaves correctly, so it has been end-to-end tested, albeit not in CI.

**Review by mhauru — APPROVED** [review]
I get paranoid about off-by-one mistakes with all index arithmetic, and testing can also guard against botched future changes. If the person who wrote the previous version would have added tests we wouldn't be here. But I do see that this is very minimal, and also it's not introducing untested functionality, it's rather fixing untested functionality, so I'm okay with merging as-is. Thanks for fixing!

**Comment by penelopeysm** [comment]
Forgot to make a release, got bitten by this 4 months later. Oops.
